name: image_build
on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '30 2 * * *'

jobs:
  prepare_release:
    runs-on: ubuntu-20.04
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - 
        id: release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: beta25
          release_name: Beta 25
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      release_id: ${{ steps.release.outputs.id }}

  release:
    runs-on: ubuntu-20.04
    needs: prepare_release
    strategy:
      matrix:
        DEVICE: [Motorola One Vision]
        EDITION: [phosh]
        BRANCH: [stable]
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - 
        id: image-build
        uses: manjaro-arm/rootfs@master
        with:
          arm-profiles-repo: https://github.com/manjaro-pinephone/arm-profiles
          device: ${{ matrix.device }}
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          version: beta25
          #CI_PUB_KEY: "${{ secrets.CI_PUB_KEY }}"
          #CI_GPG_SECRET: "${{ secrets.CI_GPG_SECRET }}"
          #CI_GPG_PASSPHRASE: "${{ secrets.CI_GPG_PASSPHRASE }}"
